### ISSUE TITLE
Inconsistency in initramfs file naming between installkernel and dracut

### ISSUE THREAD

**Issue by heroin-moose** [mgorny/installkernel-gentoo#1]
Hi,

I'm using Gentoo stable and and trying out sys-kernel/vanilla-kernel as a replacement for sys-kernel/gentoo-sources + genkernel. There is an interop issue between installkernel and dracut: installkernel puts initramfs to /boot as `/boot/initrd-<kver>` while running `dracut --force` (e.g. to rebuild initramfs after updating out-of-tree modules) produces `/boot/initramfs-<kver>.img`.

Versions:

```
$ qlist -Iv | grep -E '(dracut|installkernel|vanilla-kernel)'
sys-kernel/dracut-049-r3
sys-kernel/installkernel-gentoo-1
sys-kernel/vanilla-kernel-5.4.6-r1
```

**Comment by mgorny** [comment]
I suppose I could change it at this point since the package is quite fresh still. However, I'm a little worried of breaking existing setups. FWICS this is also what genkernel is using these days, so might be worth following suit.
